import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ConfettiProvider } from "@/components/providers/confetti-provider";
import ToastProvider from "@/components/providers/toaster-provider";
import { Navbar } from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NextJS Forum",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
            <ConfettiProvider />
            <ToastProvider />
            <Navbar />
            <main className="flex justify-between">
              <div className="flex flex-col w-full h-full">
                {children}
              </div>
              {/* <Sidebar /> */}
            </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
